### ISSUE TITLE
Xamarin Android - problem

### ISSUE THREAD

**Issue by RadiwaRami** [tobik312/GUS-lib#1]
Hi,

When running:

GUS gusClient = new GUS("XXXXX");
gusClient.Login();

I get: 

System.NullReferenceException: Object reference not set to an instance of an object.
  at GUS_lib.Utils.SOAP.getData[ReqType,ResType] (ReqType requestData, System.String customActionUrl) [0x0010d] in <bdbebb9365da4a27a83e9633425acfc6>:0 
  at GUS_lib.GUS.Login (System.Boolean force) [0x00098] in <bdbebb9365da4a27a83e9633425acfc6>:0 
  at ......
  
  Should that package work with Xamarin Android and it is up-to-date?

**Comment by tobik312** [comment]
Hi,
I didn't test this package under Xamarin Android. The GUS Api does not changed so far, soo it should work correctly.
The problem is that `SOAP.getData` method return null pointer, maybe there is problem with your internet connection on your device?

Sorry for late reply currently i do not have time to fully support this project.

**Comment by tobik312** [comment]
Hi,
I didn't test this package under Xamarin Android. The GUS API has not changed so far. It works correctly.

The problem is that the `SOAP.getDATA` method returns a null pointer, maybe there is a problem with your internet connection on your device?

Try to manually attach this library under your project, not through Nuget. This will give you a better stack trace of the error.

Sorry, for the late reply. Currently, I don't have time to fully support this project.

**Comment by RadiwaRami** [comment]
I already made my own implementation, that works, so it was not a problem of the Internet connection. 

Instead of debugging the library, it was quicker to create own solution, but I was curious, whether the library was tested in the Android.
